package Vista;

import Controlador.Ctrl_Trabajos;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class IPrincipalCom extends javax.swing.JFrame {
    private Ctrl_Trabajos ctrl_trabajos;
    public IPrincipalCom(Ctrl_Trabajos ctrl_trabajos) {
        initComponents();
        this.setLocationRelativeTo(null); 
        this.setResizable(false);
        this.setTitle("IPrincipalCom");
        this.ctrl_trabajos = ctrl_trabajos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seleccion = new javax.swing.JLabel();
        btnCargarTrabajos = new javax.swing.JButton();
        btnCargarProfesores = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnProfesoresQuePresentaron = new javax.swing.JButton();
        btnTrabajosPorCentro = new javax.swing.JButton();
        btnTrabajosPorProfesor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        seleccion.setText("Seleccione una Opción:");

        btnCargarTrabajos.setText("Cargar Trabajos");
        btnCargarTrabajos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarTrabajosActionPerformed(evt);
            }
        });

        btnCargarProfesores.setText("Cargar Profesores");
        btnCargarProfesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarProfesoresActionPerformed(evt);
            }
        });

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnProfesoresQuePresentaron.setText("Reportar Trabajos de Profesores que Presentaron");
        btnProfesoresQuePresentaron.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfesoresQuePresentaronActionPerformed(evt);
            }
        });

        btnTrabajosPorCentro.setText("Reportar Trabajos por Centro");
        btnTrabajosPorCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrabajosPorCentroActionPerformed(evt);
            }
        });

        btnTrabajosPorProfesor.setText("Reportar Trabajos por Porfesor");
        btnTrabajosPorProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrabajosPorProfesorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(seleccion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnProfesoresQuePresentaron, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTrabajosPorCentro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTrabajosPorProfesor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCargarProfesores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCargarTrabajos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(seleccion)
                .addGap(27, 27, 27)
                .addComponent(btnCargarTrabajos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(btnCargarProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTrabajosPorProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTrabajosPorCentro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProfesoresQuePresentaron, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTrabajosPorCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrabajosPorCentroActionPerformed
        ctrl_trabajos.reportesCentro();
    }//GEN-LAST:event_btnTrabajosPorCentroActionPerformed

    private void btnCargarTrabajosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarTrabajosActionPerformed
        ctrl_trabajos.cargar();
        try{
            ctrl_trabajos.cargarTrabajos();
        }catch (IOException ex){
            Logger.getLogger(IPrincipalCom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCargarTrabajosActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        ctrl_trabajos.principal();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnTrabajosPorProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrabajosPorProfesorActionPerformed
        ctrl_trabajos.reportesProf();
    }//GEN-LAST:event_btnTrabajosPorProfesorActionPerformed

    private void btnProfesoresQuePresentaronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfesoresQuePresentaronActionPerformed
        ctrl_trabajos.reportesTrabProf();
    }//GEN-LAST:event_btnProfesoresQuePresentaronActionPerformed

    private void btnCargarProfesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarProfesoresActionPerformed
         ctrl_trabajos.cargar();
        try {
            ctrl_trabajos.cargarProfesores();
        } catch (IOException ex) {
            Logger.getLogger(IPrincipalCom.class.getName()).log(Level.SEVERE, null, ex);
        }
        ctrl_trabajos.montar();
    }//GEN-LAST:event_btnCargarProfesoresActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        ctrl_trabajos.consulta();
    }//GEN-LAST:event_btnConsultarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCargarProfesores;
    private javax.swing.JButton btnCargarTrabajos;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnProfesoresQuePresentaron;
    private javax.swing.JButton btnTrabajosPorCentro;
    private javax.swing.JButton btnTrabajosPorProfesor;
    private javax.swing.JLabel seleccion;
    // End of variables declaration//GEN-END:variables

    public void ocultar() {
        this.setVisible(false);
    }
        
    /*public void deshabilitar() {
      btnCargarTrabajos.setEnabled(false);
      btnCargarProfesores.setEnabled(false);
      btnTrabajosPorProfesor.setEnabled(false);
      btnTrabajosPorCentro.setEnabled(false);
      btnProfesoresQuePresentaron.setEnabled(false);
    }*/
}

