package Vista;

import Controlador.Ctrl_Trabajos;

public class IReportesProf extends javax.swing.JFrame {
private Ctrl_Trabajos ctrl_trabajos;
    public IReportesProf(Ctrl_Trabajos ctrl_trabajos) {
        initComponents();
        this.setLocationRelativeTo(null); 
        this.setResizable(false);
        this.setTitle("IReportesProf");
        this.ctrl_trabajos = ctrl_trabajos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seleccionar = new javax.swing.JLabel();
        orden1 = new javax.swing.JRadioButton();
        orden2 = new javax.swing.JRadioButton();
        fechaI = new javax.swing.JLabel();
        fechaF = new javax.swing.JLabel();
        textoFechaI = new javax.swing.JTextField();
        textoFechaF = new javax.swing.JTextField();
        btnReporte = new javax.swing.JButton();
        trabajos = new javax.swing.JLabel();
        listaTrabajos = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        seleccionar.setText("Seleccionar Orden:");

        orden1.setText("Orden 1");

        orden2.setText("Orden 2");

        fechaI.setText("Fecha Inicio:");

        fechaF.setText("Fecha Final:");

        textoFechaI.setText("DD/MM/AAAA");
        textoFechaI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoFechaIActionPerformed(evt);
            }
        });

        textoFechaF.setText("DD/MM/AAAA");

        btnReporte.setText("Reporte");

        trabajos.setText("Trabajos:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        listaTrabajos.setViewportView(jTextArea1);

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(orden1)
                    .addComponent(seleccionar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(orden2)
                .addGap(79, 79, 79))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnVolver)
                    .addComponent(listaTrabajos, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fechaI)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(trabajos)
                                .addComponent(fechaF)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoFechaF, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoFechaI, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnReporte)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(seleccionar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orden1)
                    .addComponent(orden2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fechaI)
                            .addComponent(textoFechaI, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fechaF)
                            .addComponent(textoFechaF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(trabajos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listaTrabajos, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVolver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoFechaIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoFechaIActionPerformed

    }//GEN-LAST:event_textoFechaIActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        ctrl_trabajos.comisionInvestigacion();
    }//GEN-LAST:event_btnVolverActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel fechaF;
    private javax.swing.JLabel fechaI;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JScrollPane listaTrabajos;
    private javax.swing.JRadioButton orden1;
    private javax.swing.JRadioButton orden2;
    private javax.swing.JLabel seleccionar;
    private javax.swing.JTextField textoFechaF;
    private javax.swing.JTextField textoFechaI;
    private javax.swing.JLabel trabajos;
    // End of variables declaration//GEN-END:variables

    public void ocultar() {
        this.setVisible(false);
    }
}
